name: webapiteste-ngnix

networks:
  proxy:
    driver: bridge 

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"     
    networks:
      - proxy
  
  webapiteste1:
    image:  webapiteste-ngnix:dev
    environment:
      - SERVER=A
    networks:
      - proxy

  webapiteste2:
    image:  webapiteste-ngnix:dev
    environment:
      - SERVER=B
    networks:
      - proxy
   
   